// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	Club            *club
	ClubUser        *clubUser
	DeclarationGift *declarationGift
	DeclarationLog  *declarationLog
	User            *user
	UserOauth       *userOauth
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Club = &Q.Club
	ClubUser = &Q.ClubUser
	DeclarationGift = &Q.DeclarationGift
	DeclarationLog = &Q.DeclarationLog
	User = &Q.User
	UserOauth = &Q.UserOauth
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Club:            newClub(db, opts...),
		ClubUser:        newClubUser(db, opts...),
		DeclarationGift: newDeclarationGift(db, opts...),
		DeclarationLog:  newDeclarationLog(db, opts...),
		User:            newUser(db, opts...),
		UserOauth:       newUserOauth(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Club            club
	ClubUser        clubUser
	DeclarationGift declarationGift
	DeclarationLog  declarationLog
	User            user
	UserOauth       userOauth
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Club:            q.Club.clone(db),
		ClubUser:        q.ClubUser.clone(db),
		DeclarationGift: q.DeclarationGift.clone(db),
		DeclarationLog:  q.DeclarationLog.clone(db),
		User:            q.User.clone(db),
		UserOauth:       q.UserOauth.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Club:            q.Club.replaceDB(db),
		ClubUser:        q.ClubUser.replaceDB(db),
		DeclarationGift: q.DeclarationGift.replaceDB(db),
		DeclarationLog:  q.DeclarationLog.replaceDB(db),
		User:            q.User.replaceDB(db),
		UserOauth:       q.UserOauth.replaceDB(db),
	}
}

type queryCtx struct {
	Club            IClubDo
	ClubUser        IClubUserDo
	DeclarationGift IDeclarationGiftDo
	DeclarationLog  IDeclarationLogDo
	User            IUserDo
	UserOauth       IUserOauthDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Club:            q.Club.WithContext(ctx),
		ClubUser:        q.ClubUser.WithContext(ctx),
		DeclarationGift: q.DeclarationGift.WithContext(ctx),
		DeclarationLog:  q.DeclarationLog.WithContext(ctx),
		User:            q.User.WithContext(ctx),
		UserOauth:       q.UserOauth.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
