// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameClubUser = "bd_club_user"

// ClubUser mapped from table <bd_club_user>
type ClubUser struct {
	ID           int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GroupID      int32   `gorm:"column:group_id;not null;comment:组别ID" json:"group_id"`                                // 组别ID
	ClubID       int32   `gorm:"column:club_id;not null;comment:俱乐部ID" json:"club_id"`                                 // 俱乐部ID
	WithUserID   int32   `gorm:"column:with_user_id;not null;comment:关联的小程序用户ID" json:"with_user_id"`                  // 关联的小程序用户ID
	Username     string  `gorm:"column:username;not null;comment:用户名" json:"username"`                                 // 用户名
	Password     string  `gorm:"column:password;not null;comment:密码" json:"password"`                                  // 密码
	Salt         string  `gorm:"column:salt;not null;comment:密码盐" json:"salt"`                                         // 密码盐
	Email        string  `gorm:"column:email;not null;comment:邮箱" json:"email"`                                        // 邮箱
	Mobile       string  `gorm:"column:mobile;not null;comment:手机号" json:"mobile"`                                     // 手机号
	VestNickname string  `gorm:"column:vest_nickname;not null;comment:马甲昵称" json:"vest_nickname"`                      // 马甲昵称
	Energy       float64 `gorm:"column:energy;not null;default:0.00;comment:能量" json:"energy"`                         // 能量
	Price        float64 `gorm:"column:price;not null;default:0.00;comment:佣金价格" json:"price"`                         // 佣金价格
	LoginFailure int32   `gorm:"column:login_failure;not null;comment:失败次数" json:"login_failure"`                      // 失败次数
	LoginTime    int32   `gorm:"column:login_time;comment:登录时间" json:"login_time"`                                     // 登录时间
	LoginIP      string  `gorm:"column:login_ip;not null;comment:登录IP" json:"login_ip"`                                // 登录IP
	Token        string  `gorm:"column:token;not null;comment:Session标识" json:"token"`                                 // Session标识
	ClubFee      string  `gorm:"column:club_fee;not null;comment:已交团费的月份" json:"club_fee"`                             // 已交团费的月份
	Status       string  `gorm:"column:status;not null;default:normal;comment:状态:disabled=冻结 normal=正常" json:"status"` // 状态:disabled=冻结 normal=正常
	CreateTime   int32   `gorm:"column:create_time;comment:添加时间" json:"create_time"`                                   // 添加时间
	UpdateTime   int32   `gorm:"column:update_time;comment:修改时间" json:"update_time"`                                   // 修改时间
	DeleteTime   int32   `gorm:"column:delete_time;comment:删除时间" json:"delete_time"`                                   // 删除时间
}

// TableName ClubUser's table name
func (*ClubUser) TableName() string {
	return TableNameClubUser
}
