// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameClub = "bd_club"

// Club mapped from table <bd_club>
type Club struct {
	ID                 int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name               string     `gorm:"column:name;not null;comment:俱乐部名称" json:"name"` // 俱乐部名称
	Logo               string     `gorm:"column:logo;not null;comment:LOGO" json:"logo"`  // LOGO
	Intro              string     `gorm:"column:intro;not null;comment:简介" json:"intro"`  // 简介
	Content            string     `gorm:"column:content;not null" json:"content"`
	WxNickname         string     `gorm:"column:wx_nickname;not null;comment:微信昵称" json:"wx_nickname"`              // 微信昵称
	RealName           string     `gorm:"column:real_name;not null;comment:真实姓名" json:"real_name"`                  // 真实姓名
	Mobile             string     `gorm:"column:mobile;not null;comment:联系人手机号" json:"mobile"`                      // 联系人手机号
	ApplicantID        int32      `gorm:"column:applicant_id;not null;comment:申请人ID" json:"applicant_id"`           // 申请人ID
	Status             int32      `gorm:"column:status;not null;comment:状态:0=待审批,1=已通过,2=已驳回" json:"status"`        // 状态:0=待审批,1=已通过,2=已驳回
	AdminID            int32      `gorm:"column:admin_id;comment:审批人ID" json:"admin_id"`                            // 审批人ID
	AdminMemo          string     `gorm:"column:admin_memo;not null;comment:审批备注" json:"admin_memo"`                // 审批备注
	Version            int32      `gorm:"column:version;not null;comment:当前版本：0=免费版 1=付费版" json:"version"`          // 当前版本：0=免费版 1=付费版
	UserNumber         int32      `gorm:"column:user_number;not null;comment:当前成员数量" json:"user_number"`            // 当前成员数量
	NumberLimit        int32      `gorm:"column:number_limit;not null;default:10;comment:人数限额" json:"number_limit"` // 人数限额
	BillFee            float64    `gorm:"column:bill_fee;not null;default:0.00;comment:本次账单费用" json:"bill_fee"`     // 本次账单费用
	NextSettlementDate time.Time  `gorm:"column:next_settlement_date;comment:下次结算日期" json:"next_settlement_date"`   // 下次结算日期
	CreateTime         int32      `gorm:"column:create_time;not null;comment:添加时间" json:"create_time"`              // 添加时间
	UpdateTime         int32      `gorm:"column:update_time;not null;comment:修改时间" json:"update_time"`              // 修改时间
	DeleteTime         int32      `gorm:"column:delete_time;comment:删除时间" json:"delete_time"`                       // 删除时间
	ClubUser           []ClubUser `gorm:"foreignKey:club_id" json:"club_user"`
	User               User       `gorm:"foreignKey:applicant_id" json:"user"`
}

// TableName Club's table name
func (*Club) TableName() string {
	return TableNameClub
}
