// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameDeclarationLog = "bd_declaration_log"

// DeclarationLog mapped from table <bd_declaration_log>
type DeclarationLog struct {
	ID                   int32           `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID               int32           `gorm:"column:user_id;not null;comment:提交用户ID" json:"user_id"`                                // 提交用户ID
	ClubID               int32           `gorm:"column:club_id;not null;comment:俱乐部ID" json:"club_id"`                                 // 俱乐部ID
	DeclarationGiftID    int32           `gorm:"column:declaration_gift_id;not null;comment:礼物单ID" json:"declaration_gift_id"`         // 礼物单ID
	DeclarationProjectID int32           `gorm:"column:declaration_project_id;not null;comment:项目清单ID" json:"declaration_project_id"`  // 项目清单ID
	AcceptUserID         int32           `gorm:"column:accept_user_id;not null;comment:接单人ID" json:"accept_user_id"`                   // 接单人ID
	OwnerID              int32           `gorm:"column:owner_id;not null;comment:所属人ID" json:"owner_id"`                               // 所属人ID
	AcceptUserName       string          `gorm:"column:accept_user_name;not null;comment:接单人名称" json:"accept_user_name"`               // 接单人名称
	OwnerName            string          `gorm:"column:owner_name;not null;comment:所属陪名称" json:"owner_name"`                           // 所属陪名称
	OwnerManageUserName  string          `gorm:"column:owner_manage_user_name;not null;comment:审批管理员名称" json:"owner_manage_user_name"` // 审批管理员名称
	Price                float64         `gorm:"column:price;not null;default:0.00;comment:单价" json:"price"`                           // 单价
	Nums                 int32           `gorm:"column:nums;not null;comment:单量" json:"nums"`                                          // 单量
	NumsOld              int32           `gorm:"column:nums_old;not null;comment:未折算前的单量" json:"nums_old"`                             // 未折算前的单量
	BossName             string          `gorm:"column:boss_name;not null;comment:老板名称" json:"boss_name"`                              // 老板名称
	BossUserID           int32           `gorm:"column:boss_user_id;not null;comment:老板uid" json:"boss_user_id"`                       // 老板uid
	DeclarationGiftName  string          `gorm:"column:declaration_gift_name;not null;comment:礼物名称" json:"declaration_gift_name"`      // 礼物名称
	Amount               float64         `gorm:"column:amount;not null;default:0.00;comment:总金额" json:"amount"`                        // 总金额
	Commission           float64         `gorm:"column:commission;not null;default:0.00;comment:抽成" json:"commission"`                 // 抽成
	Rebate               float64         `gorm:"column:rebate;not null;default:0.00;comment:返利" json:"rebate"`                         // 返利
	DeclarationType      int32           `gorm:"column:declaration_type;not null;comment:报单类型:0=游戏单,1=礼物单" json:"declaration_type"`    // 报单类型:0=游戏单,1=礼物单
	Status               string          `gorm:"column:status;not null;default:0;comment:状态:0=待审批,1=已审批,2=已驳回" json:"status"`          // 状态:0=待审批,1=已审批,2=已驳回
	ApproveMemo          string          `gorm:"column:approve_memo;not null;comment:审批备注" json:"approve_memo"`                        // 审批备注
	Memo                 string          `gorm:"column:memo;not null;comment:备注" json:"memo"`                                          // 备注
	AcceptTime           int32           `gorm:"column:accept_time;comment:接单时间" json:"accept_time"`                                   // 接单时间
	AcceptEndTime        int32           `gorm:"column:accept_end_time;not null;comment:接单结束时间" json:"accept_end_time"`                // 接单结束时间
	CreateTime           int32           `gorm:"column:create_time;not null;comment:添加时间" json:"create_time"`                          // 添加时间
	UpdateTime           int32           `gorm:"column:update_time;not null;comment:修改时间" json:"update_time"`                          // 修改时间
	DeleteTime           int32           `gorm:"column:delete_time;comment:删除时间" json:"delete_time"`                                   // 删除时间
	Club                 Club            `gorm:"foreignKey:club_id" json:"club"`
	DeclarationGift      DeclarationGift `gorm:"foreignKey:declaration_gift_id" json:"declaration_gift"`
}

// TableName DeclarationLog's table name
func (*DeclarationLog) TableName() string {
	return TableNameDeclarationLog
}
