// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameUserOauth = "bd_user_oauth"

// UserOauth mapped from table <bd_user_oauth>
type UserOauth struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int32  `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                                                               // 用户ID
	Type        string `gorm:"column:type;not null;comment:类型:U=用户,P=平台,M=商家" json:"type"`                                                                        // 类型:U=用户,P=平台,M=商家
	Openid      string `gorm:"column:openid;not null;comment:平台ID" json:"openid"`                                                                                 // 平台ID
	Unionid     string `gorm:"column:unionid;not null;comment:厂商ID" json:"unionid"`                                                                               // 厂商ID
	Provider    string `gorm:"column:provider;not null;comment:服务提供者" json:"provider"`                                                                            // 服务提供者
	Platform    string `gorm:"column:platform;not null;comment:平台:H5=H5,wxOfficialAccount=微信公众号,wxMiniProgram=微信小程序,App=App，bytedanceMini=字节小程序" json:"platform"` // 平台:H5=H5,wxOfficialAccount=微信公众号,wxMiniProgram=微信小程序,App=App，bytedanceMini=字节小程序
	Gender      int32  `gorm:"column:gender;not null;comment:用户性别:0=未知,1=男性,2=女性" json:"gender"`                                                                  // 用户性别:0=未知,1=男性,2=女性
	IsSubscribe int32  `gorm:"column:is_subscribe;not null;comment:是否关注公众号:0=未关注,1=已关注" json:"is_subscribe"`                                                      // 是否关注公众号:0=未关注,1=已关注
	Nickname    string `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`                                                                               // 昵称
	Avatar      string `gorm:"column:avatar;not null;comment:头像URL" json:"avatar"`                                                                                // 头像URL
	Country     string `gorm:"column:country;not null;comment:国家" json:"country"`                                                                                 // 国家
	Province    string `gorm:"column:province;not null;comment:省" json:"province"`                                                                                // 省
	City        string `gorm:"column:city;not null;comment:城市" json:"city"`                                                                                       // 城市
	District    string `gorm:"column:district;not null;comment:区县" json:"district"`                                                                               // 区县
	LoginTime   int32  `gorm:"column:login_time;not null;comment:用户登录时间" json:"login_time"`                                                                       // 用户登录时间
	LoginCount  int32  `gorm:"column:login_count;not null;comment:用户登录次数" json:"login_count"`                                                                     // 用户登录次数
	SessionKey  string `gorm:"column:session_key;not null;comment:session_key" json:"session_key"`                                                                // session_key
	CreateTime  int32  `gorm:"column:create_time;not null;comment:添加时间" json:"create_time"`                                                                       // 添加时间
	UpdateTime  int32  `gorm:"column:update_time;not null;comment:修改时间" json:"update_time"`                                                                       // 修改时间
}

// TableName UserOauth's table name
func (*UserOauth) TableName() string {
	return TableNameUserOauth
}
