// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameUser = "bd_user"

// User mapped from table <bd_user>
type User struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username        string    `gorm:"column:username;not null;comment:用户名" json:"username"`                  // 用户名
	Nickname        string    `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`                   // 昵称
	Mobile          string    `gorm:"column:mobile;not null;comment:手机号" json:"mobile"`                      // 手机号
	Avatar          string    `gorm:"column:avatar;not null;comment:头像地址" json:"avatar"`                     // 头像地址
	RealName        string    `gorm:"column:real_name;not null;comment:真实姓名" json:"real_name"`               // 真实姓名
	WxNumber        string    `gorm:"column:wx_number;not null;comment:微信号码" json:"wx_number"`               // 微信号码
	LocationAddress string    `gorm:"column:location_address;not null;comment:定位地址" json:"location_address"` // 定位地址
	Address         string    `gorm:"column:address;not null;comment:详细地址" json:"address"`                   // 详细地址
	Model           string    `gorm:"column:model;not null;comment:手机型号" json:"model"`                       // 手机型号
	Lng             float64   `gorm:"column:lng;not null;default:0.000000;comment:经度" json:"lng"`            // 经度
	Lat             float64   `gorm:"column:lat;not null;default:0.000000;comment:纬度" json:"lat"`            // 纬度
	LoginTime       int32     `gorm:"column:login_time;not null;comment:用户登录时间" json:"login_time"`           // 用户登录时间
	LoginCount      int32     `gorm:"column:login_count;not null;comment:用户登录次数" json:"login_count"`         // 用户登录次数
	Gender          int32     `gorm:"column:gender;not null;comment:用户性别:0=未知,1=男性,2=女性" json:"gender"`      // 用户性别:0=未知,1=男性,2=女性
	CreateTime      int32     `gorm:"column:create_time;not null;comment:添加时间" json:"create_time"`           // 添加时间
	UpdateTime      int32     `gorm:"column:update_time;not null;comment:修改时间" json:"update_time"`           // 修改时间
	AlipayAccount   string    `gorm:"column:alipay_account;not null;comment:支付宝帐号" json:"alipay_account"`    // 支付宝帐号
	AlipayName      string    `gorm:"column:alipay_name;not null;comment:支付宝名称" json:"alipay_name"`          // 支付宝名称
	AlipayQrcode    string    `gorm:"column:alipay_qrcode;not null;comment:支付宝二维码" json:"alipay_qrcode"`     // 支付宝二维码
	UserOauth       UserOauth `gorm:"foreignKey:user_id" json:"user_oauth"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
