// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameClub = "ims_club"

// Club mapped from table <ims_club>
type Club struct {
	ID          int32      `gorm:"column:id;type:INTEGER" json:"id"`
	Name        string     `gorm:"column:name;type:TEXT" json:"name"`
	ApplicantID int32      `gorm:"column:applicant_id;type:INTEGER" json:"applicantId"`
	ClubUser    []ClubUser `gorm:"foreignKey:club_id" json:"club_user"`
	User        *User      `gorm:"foreignKey:id;references:applicant_id" json:"user"`
}

// TableName Club's table name
func (*Club) TableName() string {
	return TableNameClub
}
