// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameClubUser = "ims_club_user"

// ClubUser mapped from table <ims_club_user>
type ClubUser struct {
	ID     int32  `gorm:"column:id;type:INTEGER" json:"id"`
	ClubID int32  `gorm:"column:club_id;type:INTEGER" json:"clubId"`
	Name   string `gorm:"column:name;type:TEXT" json:"name"`
}

// TableName ClubUser's table name
func (*ClubUser) TableName() string {
	return TableNameClubUser
}
