// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameFormula = "ims_formula"

// Formula mapped from table <ims_formula>
type Formula struct {
	ID   int32  `gorm:"column:id;type:INTEGER" json:"id"`
	Name string `gorm:"column:name;type:TEXT" json:"name"`
	Tag  []Tag  `gorm:"foreignKey:id;joinForeignKey:formula_id;joinReferences:tag_id;many2many:tag_formula;references:id" json:"tag"`
}

// TableName Formula's table name
func (*Formula) TableName() string {
	return TableNameFormula
}
