// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameTagFormula = "ims_tag_formula"

// TagFormula mapped from table <ims_tag_formula>
type TagFormula struct {
	ID        int32 `gorm:"column:id;type:INTEGER" json:"id"`
	TagID     int32 `gorm:"column:tag_id;type:INTEGER" json:"tagId"`
	FormulaID int32 `gorm:"column:formula_id;type:INTEGER" json:"formulaId"`
}

// TableName TagFormula's table name
func (*TagFormula) TableName() string {
	return TableNameTagFormula
}
