// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameUser = "ims_user"

// User mapped from table <ims_user>
type User struct {
	ID        int32      `gorm:"column:id;type:INTEGER" json:"id"`
	Name      string     `gorm:"column:name;type:TEXT" json:"name"`
	Age       int32      `gorm:"column:age;type:INTEGER" json:"age"`
	UserOauth *UserOauth `gorm:"foreignKey:user_id" json:"user_oauth"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
